<?xml version="1.0" encoding="utf-8"?><messages><msg code="0" type="2">Start Time: Saturday, 5 October 2024 22:12:42</msg><msg code="0" type="0">Starting the generalization process...</msg><msg code="0" type="0">Classifying points...</msg><msg code="0" type="0">Found 416 junction points, 782 regular points, 52 dead-end points.</msg><msg code="0" type="0">Creating output points feature class...</msg><msg code="-2147467259" type="100">﻿Traceback (most recent call last):
﻿  File "E:\OneDrive\Research\GIS\Code\GeneralizeSegments.py", line 95, in &lt;module&gt;
﻿    junction_points, regular_points, dead_end_points = classify_points(input_fc, output_points_fc)
﻿                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
﻿  File "E:\OneDrive\Research\GIS\Code\GeneralizeSegments.py", line 28, in classify_points
﻿    create_points_fc(segments, output_points_fc, point_counts, junction_points, regular_points, dead_end_points)
﻿  File "E:\OneDrive\Research\GIS\Code\GeneralizeSegments.py", line 80, in create_points_fc
﻿    insert_cursor.insertRow([shape, code, name, num_appearances, point_type])
﻿AttributeError: __len__
</msg><msg code="0" type="0">Failed script Generalize Segments...</msg><msg code="-2147467259" type="100">Failed to execute (GeneralizeSegments).</msg><msg code="0" type="3">Failed at Saturday, 5 October 2024 22:13:00 (Elapsed Time: 18.50 seconds)</msg></messages>