<?xml version="1.0" encoding="utf-8"?><messages><msg code="0" type="2">Start Time: Tuesday, 8 July 2025 18:14:53</msg><msg code="0" type="0">Classifying points...</msg><msg code="-2147467259" type="100">﻿Traceback (most recent call last):
﻿  File "E:\git\LevellingThesis\Code\ClassifyPointsOnly.py", line 58, in &lt;module&gt;
﻿    classify_points(levelling_segments_input, source_points_input, points_classification_output, print_messages = True)
﻿  File "E:\git\LevellingThesis\Code\Utils\Generalization.py", line 599, in classify_points
﻿    unique_segments = Statistics(in_table=line_segments,out_table=r"memory\unique_segments",statistics_fields="StartPointCode FIRST;EndPointCode FIRST",case_field="SegmentCode")
﻿                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
﻿  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\analysis.py", line 3116, in Statistics
﻿    raise e
﻿  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\analysis.py", line 3110, in Statistics
﻿    gp.Statistics_analysis(
﻿  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 533, in &lt;lambda&gt;
﻿    return lambda *args: val(*gp_fixargs(args, True))
﻿                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
﻿arcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.
ERROR 000728: Field SegmentCode does not exist within table
Failed to execute (Statistics).

</msg><msg code="0" type="0">Failed script Classify Points Only...</msg><msg code="-2147467259" type="100">Failed to execute (ClassifyPointsOnly).</msg><msg code="0" type="3">Failed at Tuesday, 8 July 2025 18:14:53 (Elapsed Time: 0.80 seconds)</msg></messages>